name: Scheduled Workflow

on:
  schedule:
    - cron: '*/4 * * * *'  # Run every 4 minutes

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run code
        run: |
          rbiparser download -d "./xls"
