name: Scheduled Workflow

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run code and save output
        run: |
              rbiparser download -d "./xls" > output.txt



      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-script-output
          path: output.txt
