name: Your Workflow Name

on:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  setup-go:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v4.1.0
      with:
        go-version: # specify your Go version if needed
        go-version-file: # specify your go version file if needed
        check-latest: # specify if you want to check for the latest version
        token: ${{ github.token }}
        cache: true
        cache-dependency-path: # specify your cache dependency path if needed
        architecture: # specify your target architecture if needed
